project:
  type: website

website:
  title: "website-testing"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About this Site
        file: about.qmd


  sidebar:
    - title: Home
      logo: seurat.jpg
      contents:
        - text: Home
          file: index.qmd

    - title: About this Site
      contents:
        - text: About
          file: about.qmd
        - text: More Info
          file: about2.qmd
        - text: Bibliography
          file: about3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


